### ISSUE TITLE
CAFA-now website

### ISSUE THREAD

**Issue by dennisjomara** [cdaringe/clean-air-for-all-now#14]
[Phosphine.docx](https://github.com/cdaringe/clean-air-for-all-now/files/8710019/Phosphine.docx)
[ Arsine-Chemical of the Month.docx](https://github.com/cdaringe/clean-air-for-all-now/files/8710020/Arsine-Chemical.of.the.Month.docx)
[ Chemical of the Month-HF.docx](https://github.com/cdaringe/clean-air-for-all-now/files/8710034/Chemical.of.the.Month-HF.docx)

**Comment by cdaringe** [comment]
got it. site now has this content

**Comment by cdaringe** [comment]
Simplified format @ https://cdaringe.github.io/clean-air-for-all-now/chemical-of-the-month

**Comment by dennisjomara** [comment]
[Newsletter#1.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943894/Newsletter.1.pdf)
[Newsletter#2.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943895/Newsletter.2.pdf)
[Newsletter#3.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943896/Newsletter.3.pdf)
[CAFA NOW NEWSLETTER#4.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943897/CAFA.NOW.NEWSLETTER.4.pdf)

Newsletters in PDF format

**Comment by dennisjomara** [comment]
[Chemical.of.the.Month-HF.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943905/Chemical.of.the.Month-HF.pdf)
[Arsine-Chemical of the Month.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943906/Arsine-Chemical.of.the.Month.pdf)
[Phosphine (2).pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943907/Phosphine.2.pdf)

Chemicals of the Month in PDF Format

**Comment by dennisjomara** [comment]
[Long-Term-Exposure.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8943917/Long-Term-Exposure.pdf)

Feature Article of the Month which appears on the Home Page in PDF format.

**Comment by dennisjomara** [comment]
Under "News Media", an issue with Marcy's Letter to the Editor and B. Rockwell's Letter to the Editor. Neither one opens nor do they download. A message come up saying these are available on the web.

Not sure what format these are in or what to do about them. Please advise.

**Comment by dennisjomara** [comment]
[CRCAWlettertocomment.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8944653/CRCAWlettertocomment.pdf)

OK, I was able to find Marcy's letter to the editor and here it is in pdf format.

**Comment by dennisjomara** [comment]
Marcy's letter goes under news media

**Comment by dennisjomara** [comment]
[BarbaraRockwellLtrToEditorCC.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/8944977/BarbaraRockwellLtrToEditorCC.pdf)

I was able to find this one also. It goes under news media

**Comment by dennisjomara** [comment]
So Seth has the domain information (keys) all set up and will share them with you if he has not already done so.

**Comment by cdaringe** [comment]
@dennisjomara , all links you posted above have now been fixed to point to pdfs you added.

1. it's worth noting, there are still some dead links on the site. i was provided these links, so those are what i uploaded. if we need different links for those (mainly those going to the wayback machine), y'all will need to furnish replacement links or documents
2. no word on credentials. i'll leave it to you to personally to get these to me

**Comment by dennisjomara** [comment]
I was just in touch with Greg and he said that Seth bought cafanow a few minutes ago, so our earlier purchase must have expired. I assume Seth will give you the credentials and I told Greg that we prefer for you all to keep them and asked him to set up regular monthly payments from our Cascadia Action account.

Once the site goes up, I will check out the dead links. If it's just a matter of correcting the links, I will do that and send them to you through GitHub. If for whatever reason, that will not work for any or all of them, I will send a GitHub request to eliminate them. Depending on which one(s) are involved, I might send a replacement. And of course, we will be sending additional material over time. Thanks.

Dennis

**Comment by dennisjomara** [comment]
[CAFA NOW NEWSLETTER#5.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/9073843/CAFA.NOW.NEWSLETTER.5.pdf)

[Chemical of the Month-Intro.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/9073917/Chemical.of.the.Month-Intro.pdf)  CHRIS, PLEASE NOTE, THIS GOES JUST ABOVE THE FIRST CHEMICAL OF THE MONTH - HYDROGEN FLUORIDE AND SERVES AS THE INTRODUCTION TO THE WHOLE CHEMICAL-OF-THE MONTH SEGMENT.

[Shively-Letter.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/9073924/Shively-Letter.pdf)  CHRIS, PLEASE NOTE, THIS IS THE REPLACEMENT FOR THE DEAD LINK IN "TESTIMONIES" - THE SHIVELY LETTER.


[ Chemical of the Month-Xylene.pdf](https://github.com/cdaringe/clean-air-for-all-now/files/9074001/Chemical.of.the.Month-Xylene.pdf)

**Comment by cdaringe** [comment]
Processed!

**Comment by cdaringe** [comment]
Let's take the next batch of requests to a new issue, https://github.com/cdaringe/clean-air-for-all-now/issues
