### ISSUE TITLE
One more item for CAFA-now website

### ISSUE THREAD

**Issue by dennisjomara** [cdaringe/clean-air-for-all-now#16]
OK, here is the April Newsletter which should be the final item to put up (after newsletters 1-3, chemicals of the month and the donate button before we take a last look and then go live.
[CAFA NOW NEWSLETTER#4.docx](https://github.com/cdaringe/clean-air-for-all-now/files/8720836/CAFA.NOW.NEWSLETTER.4.docx)
.

**Comment by cdaringe** [comment]
Live @ https://cdaringe.github.io/clean-air-for-all-now/newsletters
